site_title: Acosys Consulting Services
site_logo: /img/logo.jpg
site_desc: |-
  Acosys is an Indigenous consulting firm with different ideas.
  We have expertise in business solutions, technology integration, and talent management.


  Our history of efficient delivery and satisfied clients has given us a solid foundation, on which we’ve built
  a reputation for creative and progressive solutions catering to nearly every major industry.
site_email: info@acosysconsulting.com
site_tel: (514) 744-9433 ext. 118
site_fax: (514) 744-6768
site_address_1: 'Suite 591, 100 Boulevard Alexis-Nihon'
site_address_2: 'Saint-Laurent, QC H4M 2P1'
url_twitter: 'https://twitter.com/AcosysInc'
url_linkedin: 'https://www.linkedin.com/company/acosys-consulting-service-inc./'
url_facebook: ''
