site_title: ' Services conseils Acosys'
site_logo: /img/acosys_logo_fr.jpg
site_desc: |-
  Acosys est une entreprise de consultation autochtone ayant une vision stratégique et des idées constructives hors du commun.


  Depuis le tout début, nous avons fait nos preuves en livrant nos projets de façon efficace et nos clients satisfaits nous ont donné une fondation solide sur laquelle
  nous avons bâti notre réputation à offrir des solutions créatives et progressistes répondant à presque chaque secteur principal de l’industrie.
site_email: info@acosysconsulting.com
site_tel: (514) 744-9433 ext. 118
site_fax: (514) 744-6768
site_address_1: 'Suite 591, 100 Boulevard Alexis-Nihon'
site_address_2: 'Saint-Laurent, QC H4M 2P1'
url_facebook: ''
url_twitter: 'https://twitter.com/AcosysInc'
url_linkedin: 'https://www.linkedin.com/company/acosys-consulting-service-inc./'
